### ISSUE TITLE
Parkour Hitbox - Player gets pinned

### ISSUE THREAD

**Issue by jacinta42** [ImTheCactus/Crow-Get-It-Game#49] opened 2023-10-17 12:23 UTC
hit box issue in parkour where the player can get pinned and stop moving

**Comment by Emzigma** [comment] 2023-11-03 07:38
At this time, there are insufficient notes in order to complete this bug. We (Jacinta and I) suspect it's to do with the mushroom cave parkour so I spent some time playtesting the area. Unfortunately I was unable to reproduce the bug. Therefore I was unable to solve the bug.

It's been decided to close this bug and revive it if/when it resurfaces. At this point in time we'll collect more details and be able to solve it then.

**Closed by Emzigma** 2023-11-03 07:38 UTC
Labels: Priority: Medium, Status: Not in progress, Bug
